name: CI_macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-13
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3'

    - name: Build and test mac OS
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
